schema_version = "1.0.0"
id = "fabrication_construction_draftsman_tools"
version = "0.1.0"
name = "Fabrication & Construction Draftsman Tools"
tagline = "A comprehensive toolkit for native, non-destructive URDF creation and rigging for ROS/Gazebo."
author = "Greenlex Systems Services Incorporated"
maintainer = "Greenlex Systems Services Incorporated"
type = "add-on"
license = [
  "GPL-3.0-or-later",
]
blender_version_min = "4.2.0"
website = "https://github.com/Japzon/Fabrication-Construction-Draftsman-Tools-Blender-Addon.git"

[permissions]
# Standard permissions for a typical UI addon.
# Change if your addon requires network or disk access beyond typical Blender file saving.
# files = "READ_WRITE"
# network = "READ_WRITE"
# clipboard = "READ_WRITE"
